#!/usr/bin/env bash
# this will ping an IP address passed as an argument

if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# pings the address 5 times
ping -c 5 "$1"
